name = "temple"
description = "Minimal hugo theme with focus on content and speed"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
homepage = "https://github.com/aos/temple"
tags = ["blog", "personal", "responsive", "minimal"]
features = ["highlightjs", "responsive", "black-and-white"]
min_version=0.13

[author]
    name = "Aos Dabbagh"
    homepage = "http://aos.github.io"
