name = "Slick"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
description = "A Hugo theme focused on content, cleanliness, speed, responsiveness and privacy"
homepage = "https://github.com/spookey/slick"
tags = ["blog", "personal", "responsive", "mobile", "minimal", "clean", "light", "high contrast", "typography"]
features = ["responsive", "black-and-white", "fulltext rss feed"]
min_version = "0.45"

[author]
    name = "Frieder Grie√ühammer"
    homepage = "https://www.der-beweis.de"

[original]
    name = "Temple"
    homepage = "http://aos.github.io"
    repo = "https://github.com/aos/temple"
